testenv: test
driver: selenium
browser: Chrome
desiredcaps:
    - chrome:
        - path: '/Users/xiongjunjie/Downloads/chromedriver'
          other: 'xxx'
      safari:
        - path: 'xxx'
          other: 'xx'

testcase:
    - testcase/OpenWebView.yaml
