driver: selenium # 驱动
browser: Chrome # 浏览器
isReset: True # 是否重置浏览器
saveScreenshot: False # 是否保存截图
desiredcaps:
    - chrome:
        - path: '/Users/xiongjunjie/Downloads/chromedriver'
          other: 'xxx'
      safari:
        - path: 'xxx'
          other: 'xx'

testcase:
    - TestCase/common/common.yaml
